### ISSUE TITLE
CBTS compromised

### ISSUE THREAD

**Issue by qntmpkts** [QCodefag/QCodefag.github.io#14]
Evidence from CBTS: https://8ch.net/cbts/res/256159.html

Q (according to trip) posts to /thestorm/

Screenshots are in zulu time:

- https://8ch.net/thestorm/res/6376.html#6623
![screenshot from 2018-01-06 18-33-47](https://user-images.githubusercontent.com/19355612/34642756-69a3313e-f310-11e7-87ed-ce2483c61a28.png)

```
Q !UW.yye1fxo  01/06/18 (Sat) 18:04:06 e0bc1f No.6623
THEY Divide.
WE Conquer.
Anticipated – human nature. 
Anticipated – interruptions by others.
Matlock meant to become PUBLIC.
THIS IS NOT A GAME.
CM – thank you for IDEN verification.
CM – how can a secure ‘read only’ board be set up whereby the message can be safely delivered? 
If a board was created, you verified IDEN, and control was w/ you/us, that would eliminate confusion as to IDEN/AUTH correct? 
No mod management – only info dumps. 
Fact-finding, archiving, discussion, etc. can then be done on a designated ‘follow up’ board. 
Message is all that matters.
THE GREAT AWAKENING.
Time is severely limited.
Q
```

- https://8ch.net/thestorm/res/6376.html#6658
![screenshot from 2018-01-06 18-35-04](https://user-images.githubusercontent.com/19355612/34642762-7468f0b8-f310-11e7-989e-50221369922e.png)
```
Q !UW.yye1fxo  01/06/18 (Sat) 18:08:49 e0bc1f No.6658
IMPORTANT:
NO comms w/ anyone privately.
NO comms outside of this platform.
Q
```

**Comment by qntmpkts** [comment]
Note that this confirms the Board Owner(s) of CBTS are compromised.

**Comment by qntmpkts** [comment]
Further confirmation and historical observations by CM:

- https://8ch.net/cbts/res/256159.html#q256225
![screenshot from 2018-01-06 20-26-21](https://user-images.githubusercontent.com/19355612/34643644-e56f5c48-f31f-11e7-8ef2-107941e46c69.png)
```
C!Odemonkey.  ☯ 8chan Administrator 01/06/18 (Sat) 16:19:37 1fb886 No.6196
A summary of events.
>January 2
I added super secure tripcodes. /cbts/ BO secures one.
>January 5 (Japan time)
Someone on /sudo/ pointed out that super secure tripcodes excluded capital letters, a big oversight which I fixed. I changed the code and announced it just on /sudo/. /cbts/ BO doesn't know about it and continues using the tripcode he secured, but because the code changed, his tripcode also changed - this led to confusion.
Q comes back and posts on /cbts/ normally. Post history is not the same, IP hash is not the same. /cbts/ BO assumes, incorrectly, that this is not Q, even though there are a number of reasons why a post history may start from zero, including changing VPN providers, changing VPN IP locations, using cellular data, resetting your modem, posting from a different location, using a different IP (hotel, restaurant etc.).
/cbts/ BO deletes those posts.
Then, Q goes to /pol/, where he is banned, and then /thestorm/, where he asks for verification.
Around 12 hours later, I confirm it is actually Q using his verified tripcode (still uncracked) on /thestorm/.
```

**Comment by QCodefag** [comment]
I noticed. I was doubting if he just made a human mistake (like I have done with this repository from time to time).
And then he posted this.
<img width="937" alt="bo_being_a_dick" src="https://user-images.githubusercontent.com/34404349/34644223-6e3686de-f332-11e7-8fb3-9ab9b2f67765.png">

**Comment by QCodefag** [comment]
I would be happy if the chaos ends. I have a lot of manual work right now with all these different trips/anonymous-posts, posting on various boards, code being compromised etc.

Would be great if /thestorm/ and !UW.yye1fxo are here to stay. Then I could solidify my scraping algorithms and reduce human errors.

**Comment by qntmpkts** [comment]
@QCodefag I will be pushing a pull request soon with some fairly big changes (I think you will like it). Please standby.

**Comment by qanonmap** [comment]
@QCodefag, I think thestorm color should be closer to **electric blue** or **cherenkov blue** (think Dr. Manhattan). A storm is electric, like lightning.

**Comment by qntmpkts** [comment]
With #15 merged, this issue is fully resolved.
