### ISSUE TITLE
Align post structure with 8chan

### ISSUE THREAD

**Issue by qntmpkts** [QCodefag/QCodefag.github.io#16]
Makes sense to do this....

**Comment by QCodefag** [comment]
this is already resolved in #8 right?

**Comment by qntmpkts** [comment]
No, I mean, when looking at typical json on 8chan, this is what you will find:


> "posts": [
>     {
>       "no": 0,
>       "sub": "",
>       "com": "",
>       "name": "Anonymous",
>       "time": 0,
>       "omitted_posts": 0,
>       "omitted_images": 0,
>       "sticky": 0,
>       "locked": 0,
>       "cyclical": "0",
>       "bumplocked": "0",
>       "last_modified": 0,
>       "id": "",
>       "tn_h": 0,
>       "tn_w": 0,
>       "h": 0,
>       "w": 0,
>       "fsize": 0,
>       "filename": "",
>       "ext": ".png",
>       "tim": "",
>       "fpath": 1,
>       "spoiler": 0,
>       "md5": "",
>       "resto": 0
>     }
> ]

Since we're duplicating the contents of these fields, we might as well keep the naming consistent, no?

**Comment by QCodefag** [comment]
And this json below is the one from archive.4plebs (which I used for the 4chan posts).
Totally different.

```
{
  "doc_id": "1",
  "num": "1",
  "subnum": "0",
  "thread_num": "1",
  "op": "1",
  "timestamp": "1366825828",
  "timestamp_expired": "0",
  "capcode": "N",
  "email": null,
  "name": "Anonymous",
  "trip": null,
  "title": null,
  "comment": "4plebs?",
  "poster_hash": null,
  "poster_country": null,
  "sticky": "0",
  "locked": "0",
  "deleted": "0",
  "nreplies": null,
  "nimages": null,
  "fourchan_date": "4/24/13(Wed)13:50",
  "comment_sanitized": "4plebs?",
  "comment_processed": "4plebs?",
  "formatted": false,
  "title_processed": null,
  "name_processed": "Anonymous",
  "email_processed": null,
  "trip_processed": null,
  "poster_hash_processed": null,
  "poster_country_name": false,
  "poster_country_name_processed": "",
  "media": {
    "media_id": "1",
    "spoiler": "0",
    "preview_orig": "13668258289537s.jpg",
    "media": "13668215782696.jpg",
    "preview_op": "13668258289537s.jpg",
    "preview_reply": null,
    "preview_w": "209",
    "preview_h": "250",
    "media_filename": "feelcup.jpg",
    "media_w": "645",
    "media_h": "773",
    "media_size": "51338",
    "media_hash": "UGaaniyM723FBlG4b77z/w==",
    "media_orig": "13668215782696.jpg",
    "exif": "{\"FileName\":\"d4c564ed648381f49af029c9443de206.jpg\",\"FileDateTime\":1366825827,\"FileSize\":51338,\"FileType\":2,\"MimeType\":\"image\\/jpeg\",\"SectionsFound\":\"\",\"COMPUTED\":{\"html\":\"width=\\\"645\\\" height=\\\"773\\\"\",\"Height\":773,\"Width\":645,\"IsColor\":1}}",
    "total": "2",
    "banned": "0",
    "media_status": "normal",
    "safe_media_hash": "UGaaniyM723FBlG4b77z_w",
    "remote_media_link": null,
    "media_link": "http://img.4plebs.org/boards/plebs/image/1366/82/13668215782696.jpg",
    "thumb_link": "http://img.4plebs.org/boards/plebs/thumb/1366/82/13668258289537s.jpg",
    "media_filename_processed": "feelcup.jpg"
  },
  "board": {
    "name": "4plebs discussion",
    "shortname": "plebs"
  }
}
```

I prefer having 

- a clean data model (nothing more you need)
- camelcase properties (which is the norm in javascript)
- fully written names, no abbreviations etc.

**Comment by qntmpkts** [comment]
> I prefer having
> a clean data model (nothing more you need)
> camelcase properties (which is the norm in javascript)
> fully written names, no abbreviations etc.

I see nothing wrong with this and have no counterargument to them. Closing.
