### ISSUE TITLE
It shows only a blank page with a single textbox in IE (Edge version)

### ISSUE THREAD

**Issue by hokching** [QCodefag/QCodefag.github.io#2]
The vertical scrollbar indicates the page to be kind of lengthy, but nothing can be seen
Seems to be related to the arrow syntax of ES6
Is it for Normies use? They might use IE

**Comment by QCodefag** [comment]
I know.. 
There is quite some ES6 and css3 in here, should be supported by all browsers except IE and Opera.
Looking at browser statistics these 2 are only used by around 8% of people worldwide and 6% in the US.

For the sake of development speed and keeping this project simple I'd like to stick to ES6 style.
I can add a crappy-browser warning saying. How about that?

**Comment by dmcneillie** [comment]
no. no crappy msg needed. :)

**Comment by hokching** [comment]
I think a popup alert is crappy indeed, but at least add a headline indicating the supported/non-supported browsers will be more clear

**Comment by hokching** [comment]
also, wondering if this app will be aware of Q's "drifting", he's quite funky on the 4ch/cbts thread compromise thing that he is drifting to everywhere like /pol/ or /thestorm/ or having a new trip code, for myself I've kind of lost track to him already

**Comment by qntmpkts** [comment]
> I think the app has to be manually updated for new Q posts, but I hope that it will be agile enough to keep up with Q

No, it does not need to be updated.
Q's been at 8cbts, then 8pol (when tripcodes were temporarily turned off 8cbts), and is now back at 8cbts.
The app will automatically parse the json from 8chan cbts/pol and pull them up. For the past two days, he's been on 8cbts only.

**Comment by qntmpkts** [comment]
No one uses IE or Edge. Just close this issue.
