### ISSUE TITLE
UI/UX Design

### ISSUE THREAD

**Issue by dmcneillie** [QCodefag/QCodefag.github.io#23]
Hi,
I'm a UI/UX developer. Can help with UI/UX if wanted. Let me know. dan@rooak.com

Took the code and imported into a site I own and gave it a lil facelift.
https://rooak.com/qposts/

Working to build a place to put all the resources into one place to help walk others through what's going on via news like articles on https://rooak.com

**Comment by qntmpkts** [comment]
FYI, it's impossible to read on mobile.
