### ISSUE TITLE
Please restore "Toggle Answers"

### ISSUE THREAD

**Issue by colinskow** [QCodefag/QCodefag.github.io#26]
This was very useful but disappeared in your last update. I've been doing it manually from console.

**Comment by qntmpkts** [comment]
Something wrong with the css, as it can be seen at https://qanonmap.github.io (this fork has begun to diverge).

**Comment by colinskow** [comment]
I'm thinking about creating a fork where answers can be submitted live and up-voted / down-voted. I'd also like a mechanism to correlate POTUS tweets.

**Comment by qntmpkts** [comment]
Live answer submission is not critical, as voting systems of that kind can be gamed.

As #19 indicates, tweet correlation is not an optional feature.

**Comment by qntmpkts** [comment]
> Something wrong with the css, as it can be seen at https://qanonmap.github.io (this fork has begun to diverge).

Seems I was mistaken... The toggle answers was removed when an ad (tracker?) was put in... See 925e76133623c4d292e5b90d32b806b3bcc6e8e4

**Comment by QCodefag** [comment]
Alright, added the answers back in.
I thought they were too outdated and weren't maintained..
