### ISSUE TITLE
Valid posts inexplicably removed

### ISSUE THREAD

**Issue by qntmpkts** [QCodefag/QCodefag.github.io#3]
See commit ac1039c5c1ed9d3c58c322471fbc86c4931648ec comments for missing posts (not exhaustive).

This is absolutely unacceptable for these to be removed. This can no longer be regarded as a valid collection of Q posts unless ALL posts are  reinstated immediately.

**Comment by qntmpkts** [comment]
So far, I have confirmed these five posts have been removed:

https://8ch.net/cbts/res/10820.html#10925
https://8ch.net/cbts/res/12535.html#12916
https://8ch.net/cbts/res/12535.html#13092
https://8ch.net/cbts/res/12535.html#13215
https://8ch.net/cbts/res/12535.html#13282

I also did a direct comparison to validate that these were removed. Proceeding to validate whether others have been removed.

**Comment by QCodefag** [comment]
Weird, I'm looking into it.

**Comment by QCodefag** [comment]
I had some problems with fetching archived 8chan posts.
Also the images on the archived posts on 8chan itself got removed, so I had to copy them from somewhere else.

All should be resolved now.
If you find anything missing, let me know.
