### ISSUE TITLE
42 real-time posts have disappeared

### ISSUE THREAD

**Issue by qntmpkts** [QCodefag/QCodefag.github.io#6]
They were listed yesterday, such that the total number of posts was 437. I refreshed today and the count dropped to 423, so that makes 14 gone.

The saved count starts at 391, so it would appear that the parser for pulling these up fails to pull them in properly.

Here are those that have disappeared, in order, which start from (what should be) 392 and (should) end at 405):

1. [142621](https://8ch.net/cbts/res/142052.html#142621)
2. [142639](https://8ch.net/cbts/res/142052.html#142639)
3. [142660](https://8ch.net/cbts/res/142052.html#142660)
4. [143025](https://8ch.net/cbts/res/142880.html#143025)
5. [143034](https://8ch.net/cbts/res/142880.html#143034)
6. [145363](https://8ch.net/cbts/res/145318.html#145363)
7. [145418](https://8ch.net/cbts/res/145318.html#145418)
8. [145498](https://8ch.net/cbts/res/145318.html#145498)
9. [145878](https://8ch.net/cbts/res/145318.html#145878)
10. [145882](https://8ch.net/cbts/res/145318.html#145882)
11. [145885](https://8ch.net/cbts/res/145318.html#145885)
12. [145899](https://8ch.net/cbts/res/145318.html#145899)
13. [146058](https://8ch.net/cbts/res/145318.html#146058)
14. [146127](https://8ch.net/cbts/res/145318.html#146127)

Archive for all three threads:
1. [142052](https://archive.fo/eZUAk)
2. [142880](https://archive.fo/zOGfo)
3. [145318](https://archive.fo/14de5)

Without yet reviewing how Q-tripcode posts are parsed, it would appear that the best long-term solution (other than simply updating the repo more frequently) is to back these up to a 3rd party database as real-time posts are found. Otherwise, it is possible, in such cases as these, for posts to disappear before they've been pulled in altogether (until they're recovered by using other sources).

**Comment by qntmpkts** [comment]
Now all of the following additional real-time posts are missing for a total of **36 real-time posts missing**:

1. [146147](https://8ch.net/cbts/res/146035.html#146147)
2. [146268](https://8ch.net/cbts/res/146035.html#146268)
3. [146328](https://8ch.net/cbts/res/146035.html#146328)
4. [146454](https://8ch.net/cbts/res/146035.html#146454)
5. [146599](https://8ch.net/cbts/res/146035.html#146599)
6. [148746](https://8ch.net/cbts/res/148453.html#148746)
7. [148761](https://8ch.net/cbts/res/148453.html#148761)
8. [148848](https://8ch.net/cbts/res/148453.html#148848)
9. [148994](https://8ch.net/cbts/res/148453.html#148994)
10. [154238](https://8ch.net/cbts/res/154170.html#154238)
11. [154468](https://8ch.net/cbts/res/154170.html#154468)
12. [154505](https://8ch.net/cbts/res/154170.html#154505)
13. [154535](https://8ch.net/cbts/res/154170.html#154535)
14. [154583](https://8ch.net/cbts/res/154170.html#154583)
15. [154682](https://8ch.net/cbts/res/154170.html#154682)
16. [156837](https://8ch.net/cbts/res/156622.html#156837)
17. [156848](https://8ch.net/cbts/res/156622.html#156848)
18. [156879](https://8ch.net/cbts/res/156622.html#156879)
19. [158078](https://8ch.net/cbts/res/157461.html#158078)
20. [158144](https://8ch.net/cbts/res/157461.html#158144)
21. [158096](https://8ch.net/cbts/res/157461.html#158096)
22. [158162](https://8ch.net/cbts/res/157461.html#158162)
23. [158219](https://8ch.net/cbts/res/157461.html#158219)
24. [158261](https://8ch.net/cbts/res/157461.html#158261)
25. [158439](https://8ch.net/cbts/res/158326.html#158439)
26. [158900](https://8ch.net/cbts/res/158326.html#158900)
27. [158980](https://8ch.net/cbts/res/158326.html#158980)
28. [159016](https://8ch.net/cbts/res/158326.html#159016)

Archive for all threads containing these 28 posts:

1. [146035](https://archive.is/O4XdP)
2. [148453](https://archive.is/QsS49)
3. [154170](https://archive.is/4qh0Z)
4. [156622](https://archive.is/EZo6M)
5. [157461](https://archive.is/CT45o)
6. [158326](https://archive.is/30VPz)

@QCodefag, an these be added to the repo soon?

**Comment by QCodefag** [comment]
Yes, I think I can fix this today.

**Comment by QCodefag** [comment]
I have updated the repository with the missing posts. But I have to double check some more if I didn't miss any.
Have little time these holidays.

I'm going to write a bot that downloads the images and updates the repository regularly with the new q-posts. Apparently new posts get archived quickly.

If you want to back-up the posts currently on screen: open the browser console and insert `copy(cbtsTrip8chanPosts)` [enter].
This will copy the json of all Q's 8chan posts to your clipboard.

Thanks for your help. Very much appreciated.

**Comment by qntmpkts** [comment]
Excellent. I've maintained a browser session with all 437 posts, so this should facilitate the update. I'll make a copy available at https://qntmpkts.keybase.pub.

**Comment by qntmpkts** [comment]
I received an "undefined" response in the console, so I'm now in the process of adding these manually...

**Comment by qntmpkts** [comment]
Status update:

I'm still making several changes, and nearly finished.

However, I have found at least one substantial error: post 156837 was erroneously set with the Washington Delaware picture when it was the ES at NK picture.

You can see my progress at https://qntmpkts.keybase.pub.

I will submit a pull request when complete, as there are other substantial changes I've made.

**Comment by QCodefag** [comment]
@qntmpkts 
> Edit: I received an "undefined" response in the console, so I'm now in the process of adding these manually...

The undefined response is the result of the evaluation of `copy`. `copy` is a void and thus will not return anything (hence the undefined response). However, it's a special function only implemented in the browser console (of most browsers) that copies your argument to the clipboard.

Try this:

1. open browser console
2. `copy(1)`
3. go to any text input
4. `cmd-v` / `ctrl-v`

**Comment by qntmpkts** [comment]
Response aside, it did not appear to copy all posts.
